### ISSUE TITLE
Resolver for Query.listPetsForUser

### ISSUE THREAD

**Issue by WChoy** [dabit3/aws-loft-react-native-amplify-workshop#1]
Here are the steps for creating a query that uses the current userId.
Instructions:
0) Add Global Secondary Index for UserId

0) Create "ClientId" with NO "Generate ???"

1) $ **amplify configure api**
? Please select from one of the below mentioned services **GraphQL**
? Choose an authorization type for the **API Amazon Cognito User Pool**
Use a Cognito user pool configured as a part of this project

2) Add userId to CreatePetInput signature and add listPetsForUser query
```
input CreatePetInput {
	name: String!
	description: String
	userId: String
}
...

type Query {
	...
	listPetsForUser: ModelPetConnection
	...
}
```

3) Modify for the existing "CreatePetInput" **Mutation**, by adding 
```
$util.qr($context.args.input.put("username", $ctx.identity.username))
$util.qr($context.args.input.put("userId", $ctx.identity.sub))
```
4) Attach the following to the new "listPetsForUser" **Query** 
```
{
    "version" : "2017-02-28",
    "operation" : "Query",
    "index" : "userId-index",
    "query" : {
        "expression": "userId = :name",
        "expressionValues" : {
            ":name" : $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
        }
    }
}
```

**Comment by dabit3** [comment]
Thanks @WChoy I just updated the README with the correct expressionValues! Thanks for your help :)

**Comment by WChoy** [comment]
Anytime.  
Learning a lot from your other Repos and Medium.  On Mobx and decorators from your dabit3/heard (always hated Redux)
